vim.keymap.set('n', '<leader>gtn', function() 
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
vim.keymap.set('n', '<leader>gt', function() 
    require('telescope').extensions.git_worktree.create_git_worktree()
require('telescope').extensions.git_worktree.git_worktrees()
end)
