# Setup term for programs to be able to use it
env:
  # TERM: alacritty  
  TERM: xterm-256color

window:
  opacity: 0.9
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  startup_mode: Maximized

font:
  # Normal font face - Also used to draw glyphs on tmux & VIM
  # NOTE: You may use any font you'd like but make sure the normal fonts
  # support ligatures/glyphs. That's used by tmux & VIM to provide a better
  # UI for powerline & tmux bottom bar.
  normal:
    family: JetBrains Mono
    style: Medium

  bold:
    family: JetBrains Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

  # Font size
  size: 24

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing
  # I've given in 14 spacing which fits really well with my fonts, you may change it
  # to your convenience but make sure to adjust 'glyph_offset' appropriately post that
  offset:
   x: 0      
   y: 6

  # Note: This requires RESTART
  # By default when you change the offset above you'll see an issue, where the texts are bottom
  # aligned with the cursor, this is to make sure they center align.
  # This offset should usually be 1/2 of the above offset-y being set.
  glyph_offset:
   x: 0
   # Keeping this as half of offset to vertically align the text in cursor
   y: 3

  # Better font rendering for mac
  use_thin_strokes: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Live config reload (changes require restart)
live_config_reload: true

# Setup some amazing custom key bindings here - Best thing is you can setup key bindings
# using Mac's 'command' to control your tmux.
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  # Use command + [ - to go to previous tmux window
  - { key: LBracket, mods: Command, chars: "\x02\x70" }
  # Use command + ] - to go to previous tmux window
  - { key: RBracket, mods: Command, chars: "\x02\x6e" }
  # New window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Close window
  - { key: W, mods: Command, chars: "\x02\x26" }
  # Change windows 1...0
  - { key: Key0, mods: Command, chars: "\x02\x30" }
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  # Increase & decrease font size
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  # Show all sessions
  - { key: A, mods: Command, chars: "\x02\x73" }
  # Sessionizer
  - { key: J, mods: Command, chars: "\x02\x6a" }
  - { key: K, mods: Command, chars: "\x02\x6b" }    
  # Find git worktrees  
  #- { key: J, mods: Control, chars: "\x02\x69" }

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    background: '#282828'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
